name: pass_manager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 状態管理
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  # 生体認証
  local_auth: ^2.2.0
  local_auth_android: ^1.0.37
  local_auth_darwin: ^1.2.2
  # 画面ルート管理
  go_router: ^14.1.1
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.2.2
  # ネットワークチェック
  connectivity_plus: ^5.0.2
  # QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # riverpod系
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true